<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TelemetryBlocker</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="BepInEx" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="0Harmony" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="PlayFab" />
    <Reference Include="LIV.LCK" />
  </ItemGroup>
</Project>